# Generated by Django 5.2.6 on 2025-09-16 14:05

import django.contrib.postgres.fields
import django.db.models.deletion
import ncct_backend.species_management.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compound_management', '0001_initial'),
        ('location_management', '0001_initial'),
        ('reference_management', '0002_alter_reference_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habitat',
            fields=[
                ('id', models.CharField(default=ncct_backend.species_management.models.generate_unique_id, editable=False, max_length=22, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Herbarium',
            fields=[
                ('id', models.CharField(default=ncct_backend.species_management.models.generate_unique_id, editable=False, max_length=22, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.CharField(default=ncct_backend.species_management.models.generate_unique_id, editable=False, max_length=22, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('recent_name', models.CharField(blank=True, max_length=255, null=True)),
                ('kingdom', models.CharField(default='Plantae', max_length=255)),
                ('trad_uses', models.CharField(blank=True, max_length=255, null=True)),
                ('part_used', models.CharField(blank=True, max_length=255)),
                ('family', models.CharField(max_length=255)),
                ('collection_date', models.DateField(blank=True, null=True)),
                ('collection_data', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None)),
                ('publication_status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published')], default='DRAFT', max_length=10)),
                ('is_public', models.BooleanField(default=False)),
                ('publication_date', models.DateTimeField(blank=True, null=True)),
                ('compounds', models.ManyToManyField(blank=True, related_name='species', to='compound_management.compound')),
                ('habitats', models.ManyToManyField(blank=True, related_name='species', to='species_management.habitat')),
                ('harvest_sites', models.ManyToManyField(related_name='picked_species', to='location_management.location')),
                ('references', models.ManyToManyField(blank=True, related_name='species', to='reference_management.reference')),
                ('storage_locations', models.ManyToManyField(blank=True, related_name='stored_species', to='location_management.location')),
            ],
            options={
                'verbose_name_plural': 'Species',
            },
        ),
        migrations.CreateModel(
            name='SpeciesChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changes', models.JSONField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_changes', to=settings.AUTH_USER_MODEL)),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='species_management.species')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SpeciesUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('AUTHOR', 'Author'), ('CURATOR', 'Curator'), ('PUBLISHER', 'Publisher')], max_length=10)),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='species_management.species')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('species', 'user', 'role')},
            },
        ),
        migrations.AddField(
            model_name='species',
            name='users',
            field=models.ManyToManyField(related_name='species_roles', through='species_management.SpeciesUser', to=settings.AUTH_USER_MODEL),
        ),
    ]
