# Generated by Django 4.2 on 2025-06-03 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compound_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('unique_id', models.AutoField(primary_key=True, serialize=False)),
                ('continent', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('region_state', models.CharField(max_length=255)),
                ('city_town', models.CharField(max_length=255)),
                ('place', models.CharField(max_length=255)),
                ('gps_latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('gps_longitude', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('unique_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('thesis_level', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('unique_id', models.AutoField(primary_key=True, serialize=False)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='species_management.location')),
            ],
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('unique_id', models.AutoField(primary_key=True, serialize=False)),
                ('compound_code', models.IntegerField()),
                ('collection_data', models.TextField()),
                ('ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='species_management.reference')),
            ],
        ),
        migrations.CreateModel(
            name='Herbarium',
            fields=[
                ('unique_id', models.AutoField(primary_key=True, serialize=False)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='species_management.location')),
            ],
        ),
        migrations.CreateModel(
            name='SpeciesSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='species_management.site')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='species_management.species')),
            ],
            options={
                'unique_together': {('species', 'site')},
            },
        ),
        migrations.CreateModel(
            name='SpeciesHerbarium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('herbarium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='species_management.herbarium')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='species_management.species')),
            ],
            options={
                'unique_together': {('species', 'herbarium')},
            },
        ),
        migrations.CreateModel(
            name='SpeciesCompound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compound', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compound_management.compound')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='species_management.species')),
            ],
            options={
                'unique_together': {('species', 'compound')},
            },
        ),
    ]
