# Generated by Django 4.2 on 2025-12-12 14:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('location_management', '0001_initial'),
        ('species_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='species',
            name='collection_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='species',
            name='harvest_sites',
            field=models.ManyToManyField(blank=True, related_name='picked_species', to='location_management.location'),
        ),
        migrations.AlterField(
            model_name='species',
            name='trad_uses',
            field=models.CharField(blank=True, null=True),
        ),
    ]
