# Generated by Django 4.2 on 2025-06-09 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reference_management', '__first__'),
        ('species_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='species',
            name='ref',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reference_management.reference'),
        ),
        migrations.DeleteModel(
            name='Reference',
        ),
    ]
