# Generated by Django 4.2 on 2025-08-26 06:30

import django.contrib.postgres.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reference_management', '0001_initial'),
        ('species_management', '0002_alter_species_ref_delete_reference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='species',
            name='compound_code',
        ),
        migrations.RemoveField(
            model_name='species',
            name='ref',
        ),
        migrations.AddField(
            model_name='species',
            name='family',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='species',
            name='kingdom',
            field=models.CharField(blank=True, default='Plantae', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='species',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='species',
            name='recent_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='species',
            name='references',
            field=models.ManyToManyField(related_name='species', to='reference_management.reference'),
        ),
        migrations.AlterField(
            model_name='species',
            name='collection_data',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None),
        ),
    ]
