# Generated by Django 4.2 on 2025-09-05 12:15

from django.db import migrations, models
import ncct_backend.species_management.models


class Migration(migrations.Migration):

    dependencies = [
        ('species_management', '0003_remove_species_compound_code_remove_species_ref_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='herbarium',
            name='unique_id',
        ),
        migrations.RemoveField(
            model_name='site',
            name='unique_id',
        ),
        migrations.RemoveField(
            model_name='species',
            name='unique_id',
        ),
        migrations.AddField(
            model_name='herbarium',
            name='id',
            field=models.CharField(default=ncct_backend.species_management.models.generate_unique_id, editable=False, max_length=22, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AddField(
            model_name='site',
            name='id',
            field=models.CharField(default=ncct_backend.species_management.models.generate_unique_id, editable=False, max_length=22, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AddField(
            model_name='species',
            name='id',
            field=models.CharField(default=ncct_backend.species_management.models.generate_unique_id, editable=False, max_length=22, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AddField(
            model_name='species',
            name='part_used',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='species',
            name='trad_use',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='species',
            name='family',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='speciescompound',
            name='id',
            field=models.CharField(default=ncct_backend.species_management.models.generate_unique_id, editable=False, max_length=22, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='speciesherbarium',
            name='id',
            field=models.CharField(default=ncct_backend.species_management.models.generate_unique_id, editable=False, max_length=22, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='speciessite',
            name='id',
            field=models.CharField(default=ncct_backend.species_management.models.generate_unique_id, editable=False, max_length=22, primary_key=True, serialize=False, unique=True),
        ),
    ]
