# Generated by Django 4.2 on 2025-09-05 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('species_management', '0004_remove_herbarium_unique_id_remove_site_unique_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='species',
            old_name='trad_use',
            new_name='trad_uses',
        ),
    ]
