# Generated by Django 4.2 on 2025-09-05 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('species_management', '0005_rename_trad_use_species_trad_uses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speciescompound',
            name='species',
            field=models.ForeignKey(db_column='species_id', on_delete=django.db.models.deletion.CASCADE, to='species_management.species'),
        ),
        migrations.AlterField(
            model_name='speciessite',
            name='species',
            field=models.ForeignKey(db_column='species_id', on_delete=django.db.models.deletion.CASCADE, to='species_management.species'),
        ),
    ]
