# Generated by Django 4.2 on 2025-09-05 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('species_management', '0006_alter_speciescompound_species_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speciesherbarium',
            name='species',
            field=models.ForeignKey(db_column='species_id', on_delete=django.db.models.deletion.CASCADE, to='species_management.species'),
        ),
    ]
