# Generated by Django 4.2 on 2025-09-05 19:46

from django.db import migrations, models
import ncct_backend.species_management.models


class Migration(migrations.Migration):

    dependencies = [
        ('species_management', '0008_alter_species_id_to_varchar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Habitat',
            fields=[
                ('id', models.CharField(default=ncct_backend.species_management.models.generate_unique_id, editable=False, max_length=22, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='species',
            name='habitats',
            field=models.ManyToManyField(related_name='species', to='species_management.habitat'),
        ),
    ]
