# Generated by Django 4.2 on 2025-09-05 23:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('species_management', '0009_habitat_species_habitats'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='species',
            name='publication_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='species',
            name='publication_status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published')], default='DRAFT', max_length=10),
        ),
        migrations.AlterField(
            model_name='habitat',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='speciescompound',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='species_management.species'),
        ),
        migrations.AlterField(
            model_name='speciesherbarium',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='species_management.species'),
        ),
        migrations.AlterField(
            model_name='speciessite',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='species_management.species'),
        ),
        migrations.CreateModel(
            name='SpeciesUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('AUTHOR', 'Author'), ('CURATOR', 'Curator'), ('PUBLISHER', 'Publisher')], max_length=10)),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='species_management.species')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('species', 'user', 'role')},
            },
        ),
        migrations.CreateModel(
            name='SpeciesChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changes', models.JSONField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_changes', to=settings.AUTH_USER_MODEL)),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='species_management.species')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='species',
            name='users',
            field=models.ManyToManyField(related_name='species_roles', through='species_management.SpeciesUser', to=settings.AUTH_USER_MODEL),
        ),
    ]
