# Generated by Django 4.2 on 2025-09-06 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('species_management', '0009_alter_species_references_species_id_to_varchar'),
        ('species_management', '0010_species_is_public_species_publication_date_and_more'),
    ]

    operations = [
    ]
