# Generated by Django 4.2 on 2025-09-06 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location_management', '0005_site'),
        ('reference_management', '0002_alter_reference_id'),
        ('compound_management', '0003_alter_compound_id'),
        ('species_management', '0011_merge_20250906_0132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='location',
        ),
        migrations.AlterUniqueTogether(
            name='speciescompound',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='speciescompound',
            name='compound',
        ),
        migrations.RemoveField(
            model_name='speciescompound',
            name='species',
        ),
        migrations.AlterUniqueTogether(
            name='speciesherbarium',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='speciesherbarium',
            name='herbarium',
        ),
        migrations.RemoveField(
            model_name='speciesherbarium',
            name='species',
        ),
        migrations.AlterUniqueTogether(
            name='speciessite',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='speciessite',
            name='site',
        ),
        migrations.RemoveField(
            model_name='speciessite',
            name='species',
        ),
        migrations.AlterModelOptions(
            name='species',
            options={'verbose_name_plural': 'Species'},
        ),
        migrations.AddField(
            model_name='species',
            name='compounds',
            field=models.ManyToManyField(blank=True, related_name='species', to='compound_management.compound'),
        ),
        migrations.AddField(
            model_name='species',
            name='harvest_site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='harvested_species', to='location_management.site'),
        ),
        migrations.AddField(
            model_name='species',
            name='storage_locations',
            field=models.ManyToManyField(blank=True, related_name='stored_species', to='location_management.location'),
        ),
        migrations.AlterField(
            model_name='species',
            name='habitats',
            field=models.ManyToManyField(blank=True, related_name='species', to='species_management.habitat'),
        ),
        migrations.AlterField(
            model_name='species',
            name='references',
            field=models.ManyToManyField(blank=True, related_name='species', to='reference_management.reference'),
        ),
        migrations.DeleteModel(
            name='Herbarium',
        ),
        migrations.DeleteModel(
            name='Site',
        ),
        migrations.DeleteModel(
            name='SpeciesCompound',
        ),
        migrations.DeleteModel(
            name='SpeciesHerbarium',
        ),
        migrations.DeleteModel(
            name='SpeciesSite',
        ),
    ]
