# Generated by Django 4.2 on 2025-09-06 12:54

from django.db import migrations, models
import ncct_backend.species_management.models


class Migration(migrations.Migration):

    dependencies = [
        ('species_management', '0012_remove_site_location_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Herbarium',
            fields=[
                ('id', models.CharField(default=ncct_backend.species_management.models.generate_unique_id, editable=False, max_length=22, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
