# Generated by Django 4.2 on 2025-09-08 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species_management', '0013_herbarium'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='collection_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
