# Generated by Django 4.2 on 2025-09-09 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location_management', '0005_site'),
        ('species_management', '0014_species_collection_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='species',
            name='harvest_site',
        ),
        migrations.AddField(
            model_name='species',
            name='harvest_sites',
            field=models.ManyToManyField(blank=True, null=True, to='location_management.site'),
        ),
    ]
