# Generated by Django 4.2 on 2025-09-09 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species_management', '0015_remove_species_harvest_site_species_harvest_sites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='species',
            name='trad_uses',
            field=models.CharField(blank=True, null=True),
        ),
    ]
