# Generated by Django 4.2 on 2025-09-09 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location_management', '0005_site'),
        ('species_management', '0016_alter_species_trad_uses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='species',
            name='harvest_sites',
            field=models.ManyToManyField(blank=True, related_name='picked_species', to='location_management.location'),
        ),
    ]
