# Generated by Django 4.2 on 2025-09-09 08:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('location_management', '0005_site'),
        ('species_management', '0017_alter_species_harvest_sites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='species',
            name='harvest_sites',
            field=models.ManyToManyField(related_name='picked_species', to='location_management.location'),
        ),
        migrations.AlterField(
            model_name='species',
            name='kingdom',
            field=models.CharField(default='Plantae', max_length=255),
        ),
        migrations.AlterField(
            model_name='species',
            name='part_used',
            field=models.CharField(blank=True, default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
