services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: ncct_db
      POSTGRES_USER: ncct_user
      POSTGRES_PASSWORD: ncct_password
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - ncct_network

  backend:
    build: ./backend
    env_file:
      - .env
    command: bash -c "python manage.py migrate && python manage.py create_superuser && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - mailhog
    networks:
      - ncct_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm run dev
    networks:
      - ncct_network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@nc2t.com
      PGADMIN_DEFAULT_PASSWORD: nc2t_admin
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - ncct_network

  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - ncct_network

volumes:
  postgres_data:

networks:
  ncct_network:
    driver: bridge