# Generated by Django 5.2.6 on 2025-09-16 14:05

import django.db.models.deletion
import ncct_backend.user_management.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.CharField(default=ncct_backend.user_management.models.generate_uuid_str, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('department', models.CharField(blank=True, max_length=255, null=True)),
                ('auth_code', models.CharField(blank=True, max_length=6, null=True)),
                ('auth_code_expiry', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.CharField(default=ncct_backend.user_management.models.generate_uuid_str, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('system_admin', models.CharField(max_length=255)),
                ('fieldname', models.CharField(max_length=255)),
                ('permissions', models.ManyToManyField(to='auth.permission')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
