# Generated by Django 4.2 on 2025-09-05 19:49

from django.db import migrations, models
import ncct_backend.user_management.models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.CharField(default=ncct_backend.user_management.models.generate_uuid_str, editable=False, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='role',
            name='id',
            field=models.CharField(default=ncct_backend.user_management.models.generate_uuid_str, editable=False, max_length=36, primary_key=True, serialize=False),
        ),
    ]
