# Generated by Django 4.2 on 2025-06-09 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('doi', models.CharField(blank=True, max_length=255, null=True)),
                ('thesis_level', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
