# Generated by Django 4.2 on 2025-12-12 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference_management', '0002_alter_reference_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='reference',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
