# Generated by Django 5.2.6 on 2025-09-16 14:05

import django.contrib.postgres.fields
import ncct_backend.compound_management.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compound',
            fields=[
                ('id', models.CharField(default=ncct_backend.compound_management.models.generate_unique_id, editable=False, max_length=22, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('other_names', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None)),
                ('pubchem_id', models.CharField(blank=True, max_length=255, null=True)),
                ('bio_activity', models.CharField(blank=True, max_length=255, null=True)),
                ('subclass', models.CharField(max_length=255)),
                ('compound_class', models.CharField(max_length=255)),
                ('smiles', models.TextField(unique=True)),
            ],
        ),
    ]
