# Generated by Django 4.2 on 2025-03-04 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compound',
            fields=[
                ('subclass', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('compound_class', models.CharField(max_length=255)),
                ('smiles', models.TextField()),
            ],
        ),
    ]
