# Generated by Django 4.2 on 2025-09-02 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compound_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compound',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
