# Generated by Django 4.2 on 2025-12-12 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compound_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compound',
            name='bio_activity',
            field=models.CharField(blank=True, null=True),
        ),
    ]
