# Generated by Django 4.2 on 2025-09-05 12:15

from django.db import migrations, models
import ncct_backend.compound_management.models


class Migration(migrations.Migration):

    dependencies = [
        ('compound_management', '0002_compound_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compound',
            name='id',
            field=models.CharField(default=ncct_backend.compound_management.models.generate_unique_id, editable=False, max_length=22, primary_key=True, serialize=False, unique=True),
        ),
    ]
