# Generated by Django 4.2 on 2025-09-08 14:00

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compound_management', '0003_alter_compound_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='compound',
            name='bio_activity',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='compound',
            name='other_names',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='compound',
            name='pubchem_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
