# Generated by Django 4.2 on 2025-09-09 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compound_management', '0004_compound_bio_activity_compound_other_names_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compound',
            name='bio_activity',
            field=models.CharField(blank=True, null=True),
        ),
    ]
