# Generated by Django 5.2.6 on 2025-09-16 14:05

import django.db.models.deletion
import ncct_backend.location_management.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.CharField(default=ncct_backend.location_management.models.generate_unique_id, editable=False, max_length=22, primary_key=True, serialize=False, unique=True)),
                ('continent', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(max_length=255)),
                ('region_state', models.CharField(blank=True, max_length=255)),
                ('city_town', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('zipCode', models.CharField(blank=True, max_length=255)),
                ('place', models.CharField(blank=True, max_length=255)),
                ('gps_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('gps_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.CharField(default=ncct_backend.location_management.models.generate_unique_id, editable=False, max_length=22, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sites', to='location_management.location')),
            ],
        ),
    ]
