# Generated by Django 4.2 on 2025-06-03 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('continent', models.CharField(max_length=255, null=True)),
                ('country', models.CharField(max_length=255)),
                ('region_state', models.CharField(max_length=255)),
                ('city_town', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('zipCode', models.CharField(max_length=255)),
                ('place', models.CharField(max_length=255)),
                ('gps_latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('gps_longitude', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
        ),
    ]
