# Generated by Django 4.2 on 2025-12-18 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='voucher_specimen_number',
            field=models.CharField(blank=True, help_text='Optional voucher specimen number', max_length=255, null=True),
        ),
    ]
