# Generated by Django 4.2 on 2025-06-03 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='gps_latitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='gps_longitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
    ]
