# Generated by Django 4.2 on 2025-09-05 12:15

from django.db import migrations, models
import ncct_backend.location_management.models


class Migration(migrations.Migration):

    dependencies = [
        ('location_management', '0003_alter_location_continent_alter_location_gps_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='id',
            field=models.CharField(default=ncct_backend.location_management.models.generate_unique_id, editable=False, max_length=22, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='place',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='location',
            name='region_state',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='location',
            name='zipCode',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
