# Generated by Django 4.2 on 2025-09-06 09:31

from django.db import migrations, models
import django.db.models.deletion
import ncct_backend.location_management.models


class Migration(migrations.Migration):

    dependencies = [
        ('location_management', '0004_alter_location_id_alter_location_place_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.CharField(default=ncct_backend.location_management.models.generate_unique_id, editable=False, max_length=22, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sites', to='location_management.location')),
            ],
        ),
    ]
